name: CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: Run lint and tests
        run: just ci 